site_name: Manual for celseq2
site_url: https://puriney.github.io/celseq2/
site_description: 'User manual for celseq2, a Python framework for processing CEL-Seq2 data'
site_author: 'Yun Yan'

repo_name: Puriney/celseq2
repo_url: https://github.com/Puriney/celseq2
edit_uri: edit/master/docs/

copyright: '&copy 2017 Yun Yan'
license: 'MIT'
theme: material
extra:
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  logo:
      icon: 'home'
  social:
    - type: 'github'
      link: https://github.com/Puriney
    - type: 'link'
      link: https://yanailab.org
  feature:
    tabs: true
  # font:
  #   text: 'Open Sans'
  #   code: 'Robote Mono'


# extra_css:
#     - css/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem(smart_enable=all)
  - fontawesome_markdown
  - toc(permalink=true)
  - admonition
  - codehilite
  - footnotes

pages:
  - Home: 'index.md'
  - User Guide:
    - 'Setup configuration': 'user_guide/setup_config.md'
    - 'Specify experiment table': 'user_guide/experiment_table.md'
    - 'Launch pipeline': 'user_guide/launch_pipeline.md'
    - 'Storage management': 'user_guide/storage.md'
  - About:
    - 'Reproducibility': 'about/reproducibility.md'
    - 'User experience': 'about/user_friendly.md'
    - 'Performance': 'about/performance.md'
    - 'Support other methods': 'about/support_others.md'
    - 'Release note': 'about/release_note.md'
  - FAQ: 'faq.md'
