site_name: Manual for celseq2
site_url: https://puriney.github.io/celseq2/
site_description: 'User manual for celseq2, a Python framework for processing CEL-Seq2 data'
site_author: 'Yun Yan'

repo_name: Puriney/celseq2
repo_url: https://github.com/Puriney/celseq2
edit_uri: edit/master/docs/

theme: material
extra:
    logo:
      icon: 'code'
    social:
      - type: 'github'
        link: https://github.com/Puriney
# extra_css:
#     - css/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.betterem(smart_enable=all)
  - fontawesome_markdown
  - toc(permalink=true)
  - admonition
  - codehilite

pages:
  - Home: 'index.md'
  - User Guide:
    - 'Setup configuration': 'user_guide/setup_config.md'
    - 'Specify experiment table': 'user_guide/experiment_table.md'
    - 'Launch pipeline': 'user_guide/launch_pipeline.md'
  - About:
    - 'Reproducibility': 'about/reproducibility.md'
    - 'Performance': 'about/performance.md'
    - 'User Experience': 'about/user_friendly.md'
    - 'Release Note': 'about/release_note.md'
