## Inforamtion ##
PROJECT_NAME: 'wonderful_sc'

## Sample Sheet ##
SAMPLE_SHEET: '/absolute/path/to/wonderful_experiment.tsv'

## All results are saved under <DIR_PROJ>
DIR_PROJ: '/absolute/path/to/saved/dir'

## CEL-seq2 Tech Setting ##
BC_INDEX_FPATH: '/absolute/path/to/wonderful_umi.tab'
BC_IDs_DEFAULT: '1-96'
UMI_LENGTH: 6
BC_LENGTH: 6

## Tools ##
BOWTIE2_INDEX_PREFIX: '/absolute/path/to/bowtie2_index'
BOWTIE2: '/absolute/path/to/bowtie2'

## Annotations ##
GFF: '/absolute/path/to/wonderful.gtf.gz'

## Demultiplexing ##
FASTQ_QUAL_MIN_OF_BC: 10
CUT_LENGTH: 35

## Alignment ##
ALIGNER: 'bowtie2'

## UMI Count ##
ALN_QUAL_MIN: 0

## Running Parameters ##
num_threads: 5
verbose: True
